### PR TITLE
Mayactl volume info command should be changed to mayactl volume describe #1990

### PR DESCRIPTION
**Pull request by dreamerHarshit**
**What this PR does / why we need it**:
Mayactl volume info command should be changed to mayactl volume describe #1990

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #[1990](https://github.com/openebs/openebs/issues/1990)

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sonasingh46** [comment]
@dreamerHarshit 
Thanks for the PR!
Can you please put the correct issue link in the PR description.

**Comment by dreamerHarshit** [comment]
> @dreamerHarshit
> Thanks for the PR!
> Can you please put the correct issue link in the PR description.

@sonasingh46 can you pls check it again.

**Comment by sonasingh46** [comment]
@dreamerHarshit 
Yes I can see a issue number. But putting the link itself will help reviewers to go directly to the issue for reference.

**Comment by dreamerHarshit** [comment]
@sonasingh46 done.

**Pull request merged**
