### PR TITLE
Fix golint issues in cas_pool.go

### PR DESCRIPTION
**Pull request by bombsimon**

### CODE REVIEW

**Comment by bombsimon** [comment]
Closes [Fix golint issue in cas_pool.go #1956](https://github.com/openebs/openebs/issues/1956) (reported in [openebs/openebs](https://github.com/openebs/openebs/issues/1956))

**Comment by Akash4927** [comment]
@bombsimon Thanks for the PR. 
You have to sign your commit. Please  take a look at https://github.com/openebs/maya/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by bombsimon** [comment]
Sorry, missed that! Edited the existing commit, now with sign-off footer.

**Comment by Akash4927** [comment]
@bombsimon Thanks.
One more thing, from next time please mention the file name in PR heading. 
That will help the reviewers.

**Pull request merged**
