### PR TITLE
fix(exporter): use camel case for replica status

### PR DESCRIPTION
**Pull request by utkarshmani1997**
- How does it impact end users?
The value of following time series will show 0:
`openebs_healthy_replica_count`
`openebs_degraded_replica_count`
- Where is the following observed?
This can be obeserved anywhere with `0.8.1` release
- Which output is the PR referring to?
Output of maya-exporter from `/metrics` endpoint

Ref: https://github.com/openebs/istgt/pull/211/files

**Checklist:**
- [x] Fixes openebs/openebs#2420
- [ ] Labelled this PR & related issue with `documentation` tag
- [ ] PR messages has document related information
- [ ] Labelled this PR & related issue with `breaking-changes` tag
- [ ] PR messages has breaking changes related information
- [x] Labelled this PR & related issue with `requires-upgrade` tag
- [ ] PR messages has upgrade related information
- [x] Commit has unit tests
- [ ] Commit has integration tests

Thanks to @kmova for reporting it.

Signed-off-by: Utkarsh Mani Tripathi <utkarsh.tripathi@mayadata.io>

### CODE REVIEW

**Comment by utkarshmani1997** [comment]
@AmitKumarDas done

**Comment by AmitKumarDas** [comment]
> @AmitKumarDas done

@utkarshmani1997 can you improve the PR message. It is not understood.

**Comment by AmitKumarDas** [comment]
@utkarshmani1997 can you set the milestone & appropriate labels against this PR. Does it need to be cherry picked to 0.8.x. Is it an item to be considered for upgrades?

**Comment by utkarshmani1997** [comment]
@AmitKumarDas what can i improve in PR message ?
I don't have permission to add labels and yes this need to be cherry-picked to 0.8.x

**Comment by utkarshmani1997** [comment]
Closed accidently, reopening it.

**Pull request merged**
