### PR TITLE
feat(mayactl): Adds bash completion for mayactl (#1987)

### PR DESCRIPTION
**Pull request by aswathkk**
The feature is implemented using `cobra-cli`'s builtin bash completion which fixes [#1987](https://github.com/openebs/openebs/issues/1987). Here, command `completion` is added to the `mayactl`, which will generate bash completion script.

To add mayactl autocompletion to your current shell, run `source <(mayactl completion)`.

mayactl_bash_completion

To add mayactl autocompletion to your profile, so it automatically loaded in future shells run:
```bash
echo "source <(mayactl completion bash)" >> ~/.bashrc
```

Planning to add support for other shells like `zsh` also.

### CODE REVIEW

**Comment by AmitKumarDas** [comment]
@aswathkk Can you update the PR as well commit with how the completion actually works. I expect some sample terminal command & output screenshots. This helps the docs as well.

**Comment by aswathkk** [comment]
@AmitKumarDas Thanks for the review.
I will update the PR message & commit message with a detailed instruction on how to use `completion` command.
Btw, What screenshot do you expect?

**Comment by aswathkk** [comment]
@AmitKumarDas I've updated the PR with instructions and a GIF screenshot.

**Comment by AmitKumarDas** [comment]
@aswathkk appreciate your effort!!
If bash is completed, we might merge this first. 
zsh can be a separate PR. What do you think?
cc @sonasingh46 @princerachit

**Comment by aswathkk** [comment]
Bash completion as well as zsh completion features are completed.
Only pending task is to document it properly (usage and examples).
If you think, zsh completion is to be made as a separate PR, that too can be done.

**Comment by princerachit** [comment]
Thanks for this brilliant PR @aswathkk !

**Comment by aswathkk** [comment]
Updated the PR with necessary changes for `zsh` support

**Comment by satyamz** [comment]
This is really good addition @aswathkk ! Thank you :+1:

**Pull request merged**
