### PR TITLE
fix(spc): provision cStor stripe based pools with single raid group

### PR DESCRIPTION
**Pull request by mittachaitu**
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>

## Pull Request template

Please, go through these steps before you submit a PR.

**Why is this PR required? What issue does it fix?**:
This PR is required to provision CSP with a single raid group
instead of multiple raid groups.
NOTE: One raid group can accumulate `n` blockdevices

**What this PR does?**:
This PR provision cStor stripe pool with a single raid group
instead of multiple raid groups, having multiple raid groups
for stripe based pool configuration doesn't make sense.
Even though CSP is created with multiple raid groups but
the underlying pool will be with a single raid group.

**Does this PR require any upgrade changes?**:
Currently, changes are handled in SPC to CSPC based migration.

**If the changes in this PR are manually verified, list down the scenarios covered:**:
- Provisioned SPC with stripe configuration and multiple blockdevices from a node.
- Provisioned SPC with mirror configuration and multiple blockdevices from a node
- Provisioned SPC with stripe configuration and one blockdevices from a node.

Sample output:
```sh
apiVersion: openebs.io/v1alpha1
kind: CStorPool
metadata:
  annotations:
    openebs.io/csp-lease: '{"holder":"openebs/cstor-sparse-pool-t5qw-6c4cccbff4-ffjf2","leaderTransition":1}'
  creationTimestamp: "2020-08-15T14:19:57Z"
  finalizers:
  - openebs.io/pool-protection
  generation: 5
  labels:
    kubernetes.io/hostname: 127.0.0.1
    openebs.io/cas-template-name: cstor-pool-create-default-1.13.0
    openebs.io/cas-type: cstor
    openebs.io/storage-pool-claim: cstor-sparse-pool
    openebs.io/version: 1.13.0
  name: cstor-sparse-pool-t5qw
  ownerReferences:
  - apiVersion: openebs.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: StoragePoolClaim
    name: cstor-sparse-pool
    uid: 28aa23bb-1626-4e34-86ed-933c5fff9eca
  resourceVersion: "5681"
  selfLink: /apis/openebs.io/v1alpha1/cstorpools/cstor-sparse-pool-t5qw
  uid: 387a4479-1ec7-4f9f-b193-47974b0dafc5
spec:
  group:
  - blockDevice:
    - deviceID: /var/openebs/sparse/6-ndm-sparse.img
      inUseByPool: true
      name: sparse-177b6bc2ae2dd332c7a384a02179368b
    - deviceID: /var/openebs/sparse/9-ndm-sparse.img
      inUseByPool: true
      name: sparse-2239d60eb46b3c26b0428fae4d15c88a
    - deviceID: /var/openebs/sparse/11-ndm-sparse.img
      inUseByPool: true
      name: sparse-31776c998f71e6c31e466b98331812f1
  poolSpec:
    cacheFile: /tmp/pool1.cache
    overProvisioning: false
    poolType: striped
    roThresholdLimit: 85
    thickProvisioning: false
```

**Any additional information for your reviewer?** : 
_Mention if this PR is part of any design or a continuation of previous PRs_
Due to this bug migration from SPC to CSPC has failed. For more info: https://github.com/openebs/openebs/issues/3107

**Checklist:**
- [ ] Fixes #<issue number>
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated? 
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track: 
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

### CODE REVIEW

**Review by shubham14bajpai — APPROVED** [review]
lgtm

**Review by prateekpandey14 — APPROVED** [review]
lgtm

**Review by kmova — APPROVED** [review]

**Comment by kmova** [comment]
@mittachaitu can you also add the changelog to this PR please.

**Comment by mittachaitu** [comment]
> @mittachaitu can you also add the changelog to this PR please.

Done

**Comment by sonasingh46** [comment]
The previous release based SPC will still have the multiple raid group set up for stripe and if this PR  gets merged then the SPC will not have a similar setup. Do we intend to provide upgrade changes? 
There can be inconsistent changes one due to older SPC and one due to newly provisioned SPC.

**Comment by mittachaitu** [comment]
> The previous release based SPC will still have the multiple raid group set up for stripe and if this PR gets merged then the SPC will not have a similar setup. Do we intend to provide upgrade changes?
> There can be inconsistent changes one due to older SPC and one due to newly provisioned SPC.

Correct!! Inconsistency will still there till we handled during the upgrade of SPC version...
cc: @kmova do we need to handle this during SPC upgrade/handling during migration is good enough?

**Review by sonasingh46 — APPROVED** [review]

**Pull request merged**
