### PR TITLE
Fix merge conflict

### PR DESCRIPTION
**Pull request by dungeonmaster18**
**What this PR does / why we need it**:
Fixes Merge Conflict on master branch.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes [openebs/openebs #1066](https://github.com/openebs/openebs/issues/1066)

**Special notes for your reviewer**:
/cc @kmova @AmitKumarDas

### CODE REVIEW

**Comment by AmitKumarDas** [comment]
@dungeonmaster18 Please look into https://github.com/openebs/maya/pull/234 & do the same change in master. The current changes are not correct.

**Comment by dungeonmaster18** [comment]
So I have to create pull against master and do the changes as per the #234 in master branch. If I am doing this way then I have to change only two file that is  orchprovider/k8s/v1/k8s.go
pkg/client/mapiserver/snapshot.go. If I am wrong please correct me.

**Comment by AmitKumarDas** [comment]
@dungeonmaster18 All the files i.e 5 files (as per PR 234) needs the change

**Comment by dungeonmaster18** [comment]
Okay cool....

**Pull request closed without merging**
