### PR TITLE
Correcting typo mistakes

### PR DESCRIPTION
**Pull request by ulshell**
Correcting the issue #1940

### CODE REVIEW

**Comment by satyamz** [comment]
Hi @ulshell , Thanks for the PR. You need sign the commit before you push for DCO to pass. You can amend the commit.
More on the DCO: https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by ulshell** [comment]
I am not getting exact information how to sign my work @satyamz can you please instruct me properly

**Comment by satyamz** [comment]
You have to reset the commit first:
```
git reset HEAD~ 
```
Add the changes again:
```
git add cmd/mayactl/app/command/volume_info.go
```
Set the email in the git config (One time activity):
```
git config --global user.email "MY_NAME@example.com"
```
Sign the Commit : 
```
git commit -s
```
Push you changes (probably force push)

**Comment by ulshell** [comment]
Hello @satyamz Thanks for instructing I have made changes and made commit again

**Comment by sonasingh46** [comment]
@ulshell 
Still you need to fix DCO sign issue.
You can join openebs slack channel and join #hacktoberfest2018 channel to get more help on this.
cc @ashishranjan738

**Pull request closed without merging**
