### PR TITLE
all: code improvements

### PR DESCRIPTION
**Pull request by keydrevolta**
Small review of some changes that can be made to the code to get better performance and readability. 

This also needs to decide on 2 comments what to do with the strings after them.

### CODE REVIEW

**Comment by kmova** [comment]
@keydrevolta -- would you like to ammend this PR or shall I close this one, since I see that you are pushing in the changes with new PRs?

**Comment by keydrevolta** [comment]
@kmova I'll amend It, just need to know from you guys what's the best to do in the situations that I commented on code (also need to fix the conflicts :D ).

**Comment by keydrevolta** [comment]
I think that in the first situation It'd be ok to return a new error with the edited content and on the second it'd be best to log it somewhere. Let me know what you guys think 👍

**Comment by kmova** [comment]
@keydrevolta -- in both the cases, it is good to return the errors. 
All the content under command/.. are used from mayactl (CLI).

**Comment by AmitKumarDas** [comment]
@keydrevolta Check for the conflicts if any

**Pull request merged**
