### PR TITLE
Remove commented code (#403)

### PR DESCRIPTION
**Pull request by divayprakash**
Remove commented code from volumeprovisioner/profile.go file

Fixes #403

### CODE REVIEW

**Comment by bbashy** [comment]
Duplicate of #89

**Comment by divayprakash** [comment]
@AmitKumarDas Done!

**Comment by AmitKumarDas** [comment]
Hello @divayprakash I have approved the other PR #89 just because it was triggered first.

Looking forward to your help in some other issues/features.

**Comment by divayprakash** [comment]
@AmitKumarDas Not to be pedantic but I actually bothered to claim the issue before starting work.

**Comment by bbashy** [comment]
@divayprakash My PR was added seconds after you commented. Should of also seen it when opening yours?

**Comment by divayprakash** [comment]
@bbashy The standard way of working with open source is that you claim an issue *before* you start working on it. If I'd seen your post on the issue stating that you were working on it, I wouldn't have started working on it in the first place!

**Comment by divayprakash** [comment]
However, I'm not here to start a fight. We are working to create a better community and foster projects together so some misunderstandings are bound to crop up along the way.

**Comment by bbashy** [comment]
@divayprakash It was such a quick commit that I didn't think to.

**Comment by kmova** [comment]
Thanks @divayprakash and @bbashy for the fix!!

@divayprakash, you also bring up a valid point about the need to have an community-agreed process in place. Since this was a small change, nonetheless it is "valuable opensource time". Would you be interested in contributing to the process doc, under here : https://github.com/openebs/openebs/tree/master/contribute/process, which can actually help avoid such duplicate efforts from others.

**Comment by AmitKumarDas** [comment]
@divayprakash & @bbashy, I respect each one of your invested time. It will be great to tune the contribute guidelines that stays simple yet tries to mitigate these frustrations.

**Pull request closed without merging**
