### PR TITLE
Update the Client-go to v6.0.0

### PR DESCRIPTION
**Pull request by Satvik08**
Signed-off-by: Satvik08 <satviksingh08@gmail.com>

-Update Gopkg.toml
-Dependency management using 'dep'
-Update gopkg.lock
-Workload objects have been promoted to the apps/v1 API group in Kubernetes 1.9. client-go follows this transition and allows the developer to use the latest version
-nomad has been updated to version 0.5.6
-k8s.io/api has been updated to release-1.9
-client-go has been updated to version 6.0.0

fixes: https://github.com/openebs/openebs/issues/1177

### CODE REVIEW

**Comment by Satvik08** [comment]
fixes: https://github.com/openebs/openebs/issues/1177

**Comment by utkarshmani1997** [comment]
@AmitKumarDas Have a look at this PR

**Comment by kmova** [comment]
@Satvik08 - since the issue openebs/openebs#1177 got created, it appears that we have v7.0.0 available which is compatible with K8s version 1.10. Would you like to close this PR and raise a new PR with upgrade to v7.0.0. Also in the next PR, can you make sure you have two commits:
(1) Only the modified dependency configuration files 
(2) All the updated vendor code. 

This commit-split will help with the review between modified files and auto-updated files.

**Comment by Satvik08** [comment]
Sure Sir @kmova

**Pull request closed without merging**
