### PR TITLE
Added unit test for IsInCluster in util_test.go

### PR DESCRIPTION
**Pull request by ashishranjan738**
**What this PR does / why we need it**:
This PR adds unit test for IsInCluster function present in util_test.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/openebs/openebs/issues/792

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by utkarshmani1997** [comment]
@ashishranjan738 can you fill up the PR details and also provide good commit messages.

**Comment by ashishranjan738** [comment]
Should i raise the pr once again ?

**Comment by kmova** [comment]
@ashishranjan738 -- the intent of this test is unclear. I will close this PR. Before writing the next UT, can you describe the approach and goal of the UT.

**Comment by ashishranjan738** [comment]
ok sure sir

**Pull request closed without merging**
