### PR TITLE
[WIP] Refactor build.sh

### PR DESCRIPTION
**Pull request by salonirk11**
This PR fixes issue [#2045](https://github.com/openebs/openebs/issues/2045)

### CODE REVIEW

**Comment by salonirk11** [comment]
@prateekpandey14 I cant view the Better Code Hub report. Please help me out here.

**Comment by salonirk11** [comment]
any updates here :) ?

**Comment by kmova** [comment]
@salonirk11, if you take a two arguments to the build.sh -- directory path and binary name  -- will it help in removing the multiple if/else conditions and hardcoded strings like exporter, apiserver etc.,

**Comment by sonasingh46** [comment]
@salonirk11 
Thanks for the PR. Please let us know once you done with the changes.

**Comment by sonasingh46** [comment]
@salonirk11
Closing due to inactivity. Feel free to reopen if we need to work on the same.

**Pull request closed without merging**
