### PR TITLE
[Updated] All Documents w.r.t their respective Documentation

### LINKED ISSUE #358: Proper Formatting/Editing of Documents Required
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT.

**What happened**: There are some errors in the documents, such as CONTRIBUTING.md and other files.

**What you expected to happen**: These documents should be properly formatted/edited.

**How to reproduce it (as minimally and precisely as possible)**: This can be fixed by reviewing each document and fixing the errors.

**Anything else we need to know?**: This bug has been discussed and I'm willing to take up this task.
CC: @kmova @NisantaSahoo.

### PR DESCRIPTION
**Pull request by utkarsh2102**
Signed-off-by: Utkarsh Gupta <guptautkarsh2102@gmail.com>

**What this PR does / why we need it**: This PR updates all the `41 files` w.r.t. their proper documentation. It fixes the typos, edits the missing periods and organises all the documents.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #358.

**Special notes for your reviewer**: All the documents in this repository has been updated. It either edits the missing periods or structures the pre-existing sentences. The repository is almost error free as far as the documentations are concerned.
CC: @NisantaSahoo @kmova.

### CODE REVIEW

**Comment by utkarsh2102** [comment]
Hi @mahebba.
I know, it's a huge PR but would heartily request you to review it as I've been working on this since a long time now.
I read all the original documentations and everything. And fixed the errors here.

Hoping you'd take some time out to review this PR.

**Comment by utkarsh2102** [comment]
Hi @mahebbar.
I know, it's a huge PR but would heartily request you to review it as I've been working on this since a long time now.
I read all the original documentations and everything. And fixed the errors here.

Hoping you'd take some time out to review this PR.

**Comment by utkarsh2102** [comment]
@kmova,
I didn't change any technical details.
I just added the missing periods. Nothing more.
I checked the original documents, too.
Hence, didn't change anything written their. Just the fullstops, etc.
So, do I still need to revert?

**Comment by kmova** [comment]
Yes @utkarsh2102 The vendor files are managed by `dep` tool and it automatically replaces the existing content with new content whenever the dependency (version) changes.

**Comment by kmova** [comment]
The PR has been inactive for a long time. Please reopen this PR by incorporating the review comments, if you would like to continue to fix this issue.

**Pull request closed without merging**
