### PR TITLE
Update the Client-go to v7.0.0

### PR DESCRIPTION
**Pull request by Satvik08**
- Dependency management using 'dep'.
- Workload objects have been promoted to the apps/v1 APIgroup in Kubernetes 1.10. client-go follows this transition and allows the developer to use the latest version
- Vendor files updated.
- k8.io/api has been updated to release-1.10
- k8s.io/client-go has been update to v7.0.0

### CODE REVIEW

**Comment by Satvik08** [comment]
Thanks Sir @kmova

**Comment by Satvik08** [comment]
Why do I need to change apimachinery @prateekpandey14

**Comment by prateekpandey14** [comment]
@Satvik08 client-go lib is auto-merge code from kubernetes/kubernetes repo, each client-go release supports specific k8s/apimachinery, k8s/api , kubernernetes release version.
For example client-go 0.7 supports specific k8s/apimachinery code which is 1.10,  the same way k8s/api and other k8s libs has to update , to nullify any API versioning and stability issue.

**Comment by kmova** [comment]
Upgraded to client version 8.0.0 (#437)

**Pull request closed without merging**
