### PR TITLE
Added error check

### PR DESCRIPTION
**Pull request by surajnarwade**
**What this PR does / why we need it**:

Added error checks

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by surajnarwade** [comment]
Fixes #100

**Comment by prateekpandey14** [comment]
Thanks @surajnarwade for PR.

**Comment by prateekpandey14** [comment]
@surajnarwade please run the go-fmt on  these 2 files

**Comment by surajnarwade** [comment]
@prateekpandey14 done with gofmt :)

**Comment by surajnarwade** [comment]
thanks @prateekpandey14 :)

**Pull request merged**
